# Generated by Django 4.1.4 on 2023-01-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ManyToManyField(to='data.product'),
        ),
    ]
