# Generated by Django 4.1.4 on 2023-01-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_item_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
