# Generated by Django 4.1 on 2022-08-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='information',
            field=models.TextField(blank=True),
        ),
    ]
