# Generated by Django 4.1 on 2022-08-25 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_statistic_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='grade',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
