# Generated by Django 4.1 on 2022-08-25 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='address',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='blog.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(),
        ),
    ]
