# Generated by Django 4.1 on 2022-08-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_inventory_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventory'},
        ),
    ]
