# Generated by Django 4.1 on 2022-08-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='source',
            field=models.URLField(null=True),
        ),
    ]
