# Generated by Django 4.1 on 2022-08-25 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blog_last_modified_blog_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='publisher',
        ),
        migrations.AddField(
            model_name='blog',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.publisher'),
        ),
    ]
