# Generated by Django 4.1 on 2022-08-25 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_blog_publisher_blog_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
