# Generated by Django 4.1 on 2022-08-25 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_blog_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='rating',
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='blog.author'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.publisher'),
        ),
    ]
